### ISSUE TITLE
Can you add support for unequal division with tensor parallelism for Llama 2

### ISSUE THREAD

**Issue by hydra324** [graphcore/Gradient-HuggingFace#4]
In the self-attention with tensor parallel implementaion (`modelling/attention.py`), the following check prevents me to use 12 ipus for the llama2 7B model:

```
assert (
            self.config.model.attention.heads % n_heads_groups == 0
        ), f"{self.config.model.attention.heads} % {n_heads_groups} != 0"
```

I can run it fine with 4, 8 and 16 IPUs. But with 12 IPUs it throws the following error:

```
Traceback (most recent call last):
  File "run-inference.py", line 65, in <module>
    main(args.config)
  File "run-inference.py", line 55, in main
    run_inference_popxl(config, tokenizer, hf_model=hf_model, sequence_length=2048)
  File "run-inference.py", line 15, in run_inference_popxl
    pipe = LlamaPipeline(config, hf_llama_checkpoint=hf_model, tokenizer=tokenizer)
  File "/scratch/user/u.ac/Gradient-HuggingFace/llama2-chatbot/api/pipeline.py", line 96, in __init__
    session: popxl.Session = inference(config)
  File "/scratch/user/u.ac/Gradient-HuggingFace/llama2-chatbot/inference.py", line 70, in inference
    layer_facts, layer_graph = LlamaDecoderBlockTP(config).create_graph(*embeddings_graph.graph.outputs)
  File "/scratch/user/u.ac/Gradient-HuggingFace/llama2-chatbot/modelling/decoder.py", line 28, in __init__
    self.attention = LlamaSelfAttentionTP(self.config)
  File "/scratch/user/u.ac/Gradient-HuggingFace/llama2-chatbot/modelling/attention.py", line 125, in __init__
    self.heads = LlamaAttentionHeads(config=config, replica_grouping=self.replica_grouping)
  File "/scratch/user/u.ac/Gradient-HuggingFace/llama2-chatbot/modelling/attention.py", line 44, in __init__
    assert (
AssertionError: 32 % 12 != 0
```

**Comment by payoto** [comment]
Hi @hydra324,

I don't think we can remove that check. Our implementation of Llama 2 uses Tensor parallelism (also called replica grouping), which splits the model over several IPUs in such a way that each part of the model needs to be the same shape: for that reason the number of IPUs needs to divide exactly the number of attention heads in the layers of the model in our current implementation.
There are more details about the technique in the [grouping graph replicas](https://docs.graphcore.ai/projects/popart-user-guide/en/latest/variablesettings.html?#grouping-graph-replicas) section of our docs.

I'll also note that our programming frameworks expect to execute a model on a number of IPUs which is a power of 2, so 12 IPUs would not be well supported. However if you tell me a bit more about your use case and why you want to use 12 IPUs I can see if there is something I can do to help?

**Comment by hydra324** [comment]
Hi @payoto ,

My use case is just a scaling study with IPUs. I see that the each IPU must have the same shaped tensors with Tensor parallelism. Thank you for showing me the documentation.
